Fix memory leak when unable to parse the channel list
AcademySoftwareFoundation/openexr pull request #1158
Opened 2021-09-25 03:01 UTC by kdt3rd

Fixes google OSS Fuzz 39198

Signed-off-by: Kimball Thurston <kdt3rd@gmail.com>

2021-09-25 19:35 UTC, cary-ilm requested changes

2021-09-25 19:35 UTC, cary-ilm commented on src/lib/OpenEXRCore/parse_header.c
> +            "Unable initialize attribute '%s', type 'chlist'",
Unable "to" initialized?

2021-09-25 20:10 UTC, kdt3rd commented on src/lib/OpenEXRCore/parse_header.c
> +            "Unable initialize attribute '%s', type 'chlist'",
me fail english? That unpossible!

2021-09-26 23:29 UTC, cary-ilm approved these changes
LGTM

2021-09-26 23:58 UTC, merged