Detect missing vst1q_f32_x2 and provide replacement if necessary
AcademySoftwareFoundation/openexr pull request #1358
Opened 2023-03-16 16:53 UTC by betajippity

Older versions of GCC (< 9) do not provide the vst1q_f32_x2 intrinsic on aarch64, so we must detect when vst1q_f32_x2 is not available and provide our own implementation instead.

2023-03-16 21:57 UTC, cary-ilm commented
Thanks for the fix, but see the suggestions above.

2023-03-17 01:17 UTC, betajippity commented
> Thanks for the fix, but see the suggestions above.

Which suggestions? I don't see any; apologies if I'm looking in the wrong place.

2023-03-17 15:22 UTC, cary-ilm requested changes

2023-03-17 15:22 UTC, cary-ilm commented on cmake/OpenEXRSetup.cmake
> +    string(APPEND CMAKE_CXX_FLAGS " -DMISSING_ARM_VLD1")
This would be better as a CMake-generated define rather than a compiler flag:

```suggestion
    set(OPENEXR_MISSING_ARM_VLD1" 1)
```
Then add:
```
    #cmakedefine OPENEXR_MISSING_ARM_VLD1 0
```
to ``cmake/OpenEXRConfigInternal.h.in``

2023-03-17 15:22 UTC, cary-ilm commented on src/lib/OpenEXR/ImfSimd.h
> +#if defined (MISSING_ARM_VLD1)
... and change this to ``OPENEXR_MISSING_ARM_VLD1`` to identify it as an OpenEXR config thing.

2023-03-17 15:23 UTC, cary-ilm commented
Oops, I neglected to submit the review, sorry. Should be there now.

2023-03-20 18:03 UTC, betajippity commented
Whoops, sorry for the bevy of build test failures. I didn't realize that pushing a WIP to the branch on my fork would automatically update the merge request and kick off tests here!

2023-03-20 18:26 UTC, betajippity commented on cmake/OpenEXRSetup.cmake
> +    string(APPEND CMAKE_CXX_FLAGS " -DMISSING_ARM_VLD1")
These notes are now implemented; the flag is now set as a CMake-generated define and is in `cmake/OpenEXRConfigInternal.h.in`.

2023-03-20 18:27 UTC, betajippity commented on src/lib/OpenEXR/ImfSimd.h
> +#if defined (MISSING_ARM_VLD1)
This change is now implemented; the flag is now named `OPENEXR_MISSING_ARM_VLD1`.

2023-03-20 23:44 UTC, cary-ilm approved these changes
LGTM, thanks!

2023-03-20 23:44 UTC, merged