Add CMake Export file to install step in IlmBase and OpenEXR
AcademySoftwareFoundation/openexr pull request #368
Opened 2019-01-22 18:55 UTC by hjmallon

I am beginning work on adding ilmbase and openexr to hunter. See https://github.com/ruslo/hunter/issues/361
If this were to be merged then I might be able to avoid forking the repo as it is needed by some CMake packaging tools.

2019-01-23 19:08 UTC, hjmallon commented
Reset to WIP as still testing.

2019-01-24 22:25 UTC, hjmallon commented
I am now happy with this. With this plus a couple of other changes (which I can send separately) I was able to get IlmBase and OpenEXR to build with hunter.

EDIT: I have updated again below. I really could do with someone who knows this CMake packaging stuff well to give this a review.

2019-01-25 13:31 UTC, hjmallon commented
This is similar to #167 and #178 (but I have made fewer sweeping changes for now, they could come in a second PR if required). Maybe @AWhetter might be interested to see it?

2019-01-30 05:48 UTC, AWhetter commented
Very nice! I would love to see this merged if my pull requests get rejected for whatever reason.

2019-02-06 13:05 UTC, hjmallon commented
I agree with @AWhetter that his more fully featured Pull Req is preferable.

2019-05-15 09:51 UTC, ruslo requested changes

2019-05-15 09:51 UTC, ruslo commented on IlmBase/Config.cmake.in
> +include("${CMAKE_CURRENT_LIST_DIR}/@TARGETS_EXPORT_NAME@.cmake")
From [documentation](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#generating-a-package-configuration-file):
```
check_required_components(<PackageName>) should be called at the end of the
FooConfig.cmake file ... This macro should be called even if the package
doesn’t provide any components to make sure users are not specifying components
erroneously.
```

Example:
- https://github.com/forexample/package-example/blob/00335ff3f39c3b82a4b4b6095412b5a9e3aeda81/Foo/cmake/Config.cmake.in

2019-05-15 09:51 UTC, ruslo commented on IlmBase/Half/CMakeLists.txt
> +      INCLUDES DESTINATION include/OpenEXR
This one will modify `INTERFACE_INCLUDE_DIRECTORIES`. I'm not sure about C++ part but usually it's just `include`, e.g.:
- https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-packages

2019-05-15 10:46 UTC, hjmallon commented
Thanks for the review @ruslo . I think something based on @AWhetter 's version with a more complete overhaul is probably more desirable.

2019-07-17 13:34 UTC, kdt3rd commented
I have completely refactored the cmake infrastructure for openexr to use the "modern cmake" paradigm. If you could take a look at the current master, and see if I missed something about the config mechanism, would be much appreciated.

2019-07-21 06:37 UTC, kdt3rd commented
The complete refactor of the cmake build has been completed and merged onto master. If there are any issues with the new export mechanism, please report them as bugs / new PRs. Thanks for all the contributions!

2019-07-21 06:37 UTC, closed without merging