Include <limits> where required by newer compilers
AcademySoftwareFoundation/openexr pull request #893
Opened 2021-01-12 19:29 UTC by cary-ilm

Signed-off-by: Cary Phillips <cary@ilm.com>

2021-01-12 20:45 UTC, meshula requested changes
Almost ready, two redundancies though

2021-01-12 20:45 UTC, meshula commented on src/lib/OpenEXR/ImfDeepScanLineInputFile.cpp
>  #include <limits>
This one isn't needed, it appears at line 69

2021-01-12 20:45 UTC, meshula commented on src/lib/OpenEXR/ImfDeepTiledInputFile.cpp
> +#include <limits>
ditto, line 65

2021-01-13 21:05 UTC, cary-ilm commented on src/lib/OpenEXR/ImfDeepTiledInputFile.cpp
> +#include <limits>
Done, thanks. Flying blind, I can't actually reproduce these errors.

2021-01-13 21:06 UTC, merged